# -------------------------------------------------------------
# |                                                           |
# |                        ETERNAL ORE                        |
# |                                                           |
# |     This file is used to configure the different types    |
# |     ores that can regenerate in EternalOre. Please do     |
# |     Not remove anything as doing so will cause errors.    |
# |                                                           |
# -------------------------------------------------------------

# The material of the wand item for this plugin.
wand-material: BLAZE_ROD

# The block that will take the place of the mined ore until it respawns.
placeholder-block: BEDROCK

# The settings for the mineable ores.
ores:
  stone:
    drop: STONE
    max-drop-count: 1
    respawn-time: 1
  cobblestone:
    drop: COBBLESTONE
    max-drop-count: 1
    respawn-time: 1
  quartz-ore:
    drop: QUARTZ
    max-drop-count: 1
    respawn-time: 1
  coal-ore:
    drop: COAL
    max-drop-count: 1
    respawn-time: 1
  iron-ore:
    drop: IRON_INGOT
    max-drop-count: 1
    respawn-time: 2
  gold-ore:
    drop: GOLD_INGOT
    max-drop-count: 1
    respawn-time: 5
  lapis-ore:
    drop: LAPIS_LAZULI
    max-drop-count: 1
    respawn-time: 5
  redstone-ore:
    drop: REDSTONE
    max-drop-count: 1
    respawn-time: 5
  diamond-ore:
    drop: DIAMOND
    max-drop-count: 1
    respawn-time: 7
  emerald-ore:
    drop: EMERALD
    max-drop-count: 1
    respawn-time: 10
  random-ore:
    ores:
      - COAL_ORE
      - IRON_ORE
      - GOLD_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
    max-drop-count: 10
    respawn-time: 15